steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build", "-t",
      "asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/hello-tonik:$SHORT_SHA",
      "."
    ]

  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/hello-tonik:$SHORT_SHA"
    ]

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "container", "clusters", "get-credentials", "staging-cluster",
      "--zone", "asia-southeast1", "--project", "western-emitter-461905-e7"
    ]

  - name: "gcr.io/cloud-builders/kubectl"
    args: [
      "set", "image", "deployment/hello-tonik-deployment",
      "hello-tonik=asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/hello-tonik:$SHORT_SHA",
      "--namespace=cicd-test-service"
    ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast1"
      - "CLOUDSDK_CONTAINER_CLUSTER=staging-cluster"

images:
  - "asia-southeast1-docker.pkg.dev/western-emitter-461905-e7/cicd-testing/hello-tonik:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
